// Vendor Configuration - Generated by miShop Generator
// Address is obfuscated to prevent tampering

const VENDOR_CONFIG = {
    obfuscatedAddress: "PLACEHOLDER",
    salt: "PLACEHOLDER",
    obfuscatedApiKey: "",
    vendorPublicKey: "PLACEHOLDER",
    appName: "miShop",
    version: "1.0.0"
};
