// Product Configuration - Generated by miniMerch CLI
// DO NOT EDIT - Regenerate using: mini-merch generate or mini-merch generate-multi

// Slippage buffer applied to Minima payments at checkout (vendor-defined %)
const SLIPPAGE_RATE = 10;

const PRODUCTS = [
    {
        name: "Placeholder Product",
        description: "A great product from miniMerch",
        mode: "weight",
        pricePerGram: 10,
        pricePerUnit: 0,
        totalWeight: 28,
        maxUnits: 10,
        image: "item.jpg",
        sizes: [
            { id: "full",    name: "Full",    weight: 28,   multiplier: 1.0,   percentage: 100 },
            { id: "half",    name: "Half",    weight: 14,   multiplier: 0.5,   percentage: 50 },
            { id: "quarter", name: "Quarter", weight: 7,    multiplier: 0.25,  percentage: 25 },
            { id: "eighth",  name: "Eighth",  weight: 3.5,  multiplier: 0.125, percentage: 12.5 }
        ],
        rebroadcastDelayHours: 2,
        rebroadcastMaxIntervalHours: 24,
        firstRebroadcastDelayHours: 2,
        created: "2024-01-01T00:00:00.000Z"
    }
];

// Backward-compat alias — single-product shops use this directly
// Declared as let so the carousel can reassign it when navigating products
let PRODUCT = PRODUCTS[0];

function calculateSizesForWeight(totalWeight) {
    return [
        { id: "full",    name: "Full",    weight: totalWeight,       multiplier: 1.0,   percentage: 100 },
        { id: "half",    name: "Half",    weight: totalWeight / 2,   multiplier: 0.5,   percentage: 50 },
        { id: "quarter", name: "Quarter", weight: totalWeight / 4,   multiplier: 0.25,  percentage: 25 },
        { id: "eighth",  name: "Eighth",  weight: totalWeight / 8,   multiplier: 0.125, percentage: 12.5 }
    ];
}

function getPriceForSize(sizeId, product) {
    const p = product || PRODUCT;
    const size = p.sizes.find(s => s.id === sizeId);
    if (!size) return 0;
    if (p.mode === 'units') return p.pricePerUnit * size.weight;
    return p.pricePerGram * size.weight;
}
